### ISSUE TITLE
GWAS_QC enhancement

### ISSUE THREAD

**Issue by dianacornejo** [cumc/bioworkflows#40]
@gaow I would suggest to add a suffix when running QC for related individuals

```
sos run GWAS_QC.ipynb qc:1 \
    --cwd ~/output \
    --genoFile MWE_AD/rename_chr22.bed \
    --keep-samples  ~/output/rename_chr22.related_id\
    --keep-variants ~/output/cache/rename_chr22.filtered.prune.in \
    --maf-filter 0 --geno-filter 0 --mind-filter 0 --hwe-filter 0 \
    --container_lmm /mnt/mfs/statgen/containers/lmm.sif
```
It happened to me that I overwrote the results generated before by the related, and didn't realized that until I was doing the projection_step, which off course is going to be wrong since the initial PCA was already calculated with the related samples and not the unrelated ones.

**Comment by gaow** [comment]
@dianacornejo i see .. one option is to force users to provide a suffix; another option is to create one bsaed on the keep-samples and keep-variats options; but again you have those filters which might be different too. ... I agree it is cleaner to just ask for a suffix, or a `name` tag. Doing this in a minute.

**Comment by gaow** [comment]
@dianacornejo I now added a required input parameter `--name`. That should serve our purpose.
