### ISSUE TITLE
Possible fix PCA pipeline depending on type of data

### ISSUE THREAD

**Issue by dianacornejo** [cumc/bioworkflows#42]
@haoyueshuai there's a possible fix in this line. In the UKBB FID and IID are the same, but this does not hold true for family data as the one you are working with. So you might need to change this part. 
https://github.com/cumc/bioworkflows/blob/1a01ef16f98914f4b1f2f61ecccfbc961ad4096b/GWAS/PCA.ipynb#L748

**Comment by haoyueshuai** [comment]
@dianacornejo Got it, thank you!
